#!/bin/bash
# tested against  a AWS EC2 instance with a Linux 2 VM (Ubuntu)

set -eu
trap "{ echo 'ERROR - H2O Flow UI action failed' ; exit 255; }" SIGINT SIGTERM ERR

# TODO check h2o for existence
# TODO check java for existence

[[ $# -eq 1 ]] || { echo 'ERROR - H2O Flow missing action'; exit 255; }

action=$1

case $action in
  start)
    #TODO timestamp sur le log
    ! tmux has-session -t h2oflow 2>/dev/null && {
      echo "=== starting H2O Flow Web UI"
      tmux new -d -s h2oflow bash -c "cd /opt/h2o/h2oflowui; java -jar h2o.jar 2>&1  | tee -a /var/log/aidemos/h2o/h2oflowui.out" &
      echo "INFO - H2O started"
    }
    # TODO check for existence
    ;;
  stop)
    ! tmux has-session -t h2oflow  2>/dev/null && {
      #TODO log arret
      echo "=== stopping H2O Flow"
      tmux kil-session -t h2oflow
      echo "INFO - H2O Flow stopped"
    }
    ;;
  *)
    echo "ERROR - unknow action action"
    exit -1
    ;;
esac
