name: python36
channels:
  - h2oai
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - anaconda
  - mlflow
  - airflow
  - h2o
  - colorama >=0.3.7
  - future >=0.15.2
  - tabulate >=0.7.5
  - requests >=2.10
  - setuptools
  - flask
  - pip

