#!/bin/bash
# tested against  a AWS EC2 instance with a Linux 2 VM (Ubuntu)
# run a jupyter

set -eu
trap "{ echo 'ERROR - Jupyter action failed' ; exit 255; }" SIGINT SIGTERM ERR

[[ $# -eq 1 ]] || { echo 'ERROR - Jupyter missing action'; exit 255; }

action=$1

case $action in
  start)
    #TODO timestamp sur le log
    ! tmux has-session -t jupyter  2>/dev/null && {
      echo "=== starting Jupyter"
      tmux new -d -s jupyter bash -c 'cd /opt/jupyter; source etc/setenv.sh; jupyter notebook --notebook-dir=/data/aidemos/ --no-browser --ip 0.0.0.0 2>&1 | tee -a /var/log/aidemos/jupyter/jupyter.out' &
      # show token
      #tmux new -d -s jupyter-list bash -c 'cd /opt/jupyter; source etc/setenv.sh; jupyter notebook list'
      echo "INFO - Jupyter started"
    }
    # TODO check for existence
    ;;
  stop)
    ! tmux has-session -t jupyter  2>/dev/null && {
      #TODO log arret
      echo "=== stopping Jupyter"
      tmux kil-session -t jupyter
      echo "INFO - Jupyter stopped"
    }
    ;;
  attach)
      tmux attach -t jupyter
      ;;
  list)
      tmux new -d -s jupyter-list bash -c 'cd /opt/jupyter; source etc/setenv.sh; jupyter notebook list'
      ;;
  *)
    echo "ERROR - unknow action $action"
    exit -1
    ;;
esac
